-- AlterTable
ALTER TABLE `transfers` MODIFY `reject_reason` ENUM('INSUFFICIENT_BALANCE', 'INVALID_RECIPIENT', 'INVALID_SENDER', 'SENDER_NOT_ACTIVE', 'RECIPIENT_NOT_ACTIVE', 'SELF_TRANSFER', 'INVALID_REQUEST') NULL;
